version: '3.8'
services:
  app:
    build:
      context: .
      args:
        - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
        - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
        - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
        - GITHUB_OWNER=${GITHUB_OWNER}
        - GITHUB_REPO=${GITHUB_REPO}
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    ports:
      - "3000:3000" 